name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.latam-challenge-448016 }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.latam-challenge-448016 }}/latam-challenge-api .
        docker push gcr.io/${{ secrets.latam-challenge-448016 }}/latam-challenge-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy latam-challenge-api \
          --image gcr.io/${{ secrets.latam-challenge-448016 }}/latam-challenge-api \
          --platform managed \
          --region ${{ secrets.southamerica-west1 }} \
          --allow-unauthenticated
